### ISSUE TITLE
Source generation error with Visual Studio

### ISSUE THREAD

**Issue by geertdoornbos** [mhdbouk/source-generator-demo#1]
The source generation does not work with Visual Studio. It does work when using netstandard 2.0.

```
<TargetFramework>netstandard2.0</TargetFramework>
```

This [issue](https://github.com/dotnet/roslyn/issues/47087#issuecomment-679280683) does not seem to be fixed.

[Documentation](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) shows a warning: **Currently only .NET Standard 2.0 assemblies can be used as Source Generators.**

Nice demo btw 👍

**Comment by mhdbouk** [comment]
Oh, that’s interesting. I tried `netstandard2.1` and it worked. I thought the documentation was not updated (as usual 😅), but it was Rider doing the job. I didn’t know that Visual Studio would not work.
Thank you for the heads up. I will update the code with `netstandard2.0`
